# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: lmaria <lmaria@student.42.fr>              +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/12/05 14:17:12 by lmaria            #+#    #+#              #
#    Updated: 2024/12/09 16:41:16 by lmaria           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

.PHONY: all compile_submake clean fclean

# Nom du Makefile à compiler
SUBMAKEFILE = Libft/Makefile

MAKEFILE = ft_printf/Makefile

# Nom de l'exécutable
NAME = libftprintf.a
SUBNAME = $(shell $(MAKE) --no-print-directory -C Libft print-nameexec)


# Répertoires
OBJ_DIR = obj

#Options de compilation
CC = cc
CFLAGS = -Wall -Werror -Wextra

# Fichiers source
PRINTF_SRC  = \
	ft_printf.c \
	ft_printf_utils.c

# Fichiers objets
OBJ = $(addprefix $(OBJ_DIR)/, $(PRINTF_SRC:.c=.o))

# Règles
all: compile_submake $(NAME)

$(NAME) : $(OBJ)
	@echo "Compiling the Makefile : $(MAKEFILE)"
	@cp Libft/$(SUBNAME) $(NAME)
	@ar rcs $@ $^
	@echo "Executable $(NAME) created with $(SUBNAME)."
	
$(OBJ_DIR)/%.o: %.c | $(OBJ_DIR)
	@$(CC) $(CFLAGS) -c $< -o $@

$(OBJ_DIR):
	@mkdir -p $(OBJ_DIR)

# Règle pour appeler un autre Makefile
compile_submake:
	@echo "Compiling the Makefile : $(SUBMAKEFILE)"
	@$(MAKE) --no-print-directory -C Libft

# Nettoyage général
clean:
	@echo "Delete object files generated by $(SUBMAKEFILE) and $(MAKEFILE)."
	@$(MAKE) --no-print-directory -C Libft clean
	@rm -rf $(OBJ_DIR)

fclean: clean
	@echo "Delete complete (including $(SUBNAME) and $(NAME))."
	@$(MAKE) --no-print-directory -C Libft fclean
	@rm -f $(NAME)
	

re: fclean all
