# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: lmaria <lmaria@student.42.fr>              +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/12/05 14:17:12 by lmaria            #+#    #+#              #
#    Updated: 2024/12/16 14:56:50 by lmaria           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

.PHONY: all compile_submake clean fclean


SUBMAKEFILE = Libft/Makefile

MAKEFILE = ft_printf/Makefile


NAME = libftprintf.a
SUBNAME = $(shell $(MAKE) --no-print-directory -C Libft print-nameexec)


CC = cc
CFLAGS = -Wall -Werror -Wextra


PRINTF_SRC  = \
	ft_printf.c \
	ft_printf_utils.c


OBJ = $(PRINTF_SRC:.c=.o)


all: compile_submake $(NAME)

$(NAME) : $(OBJ)
	@echo "Compiling the Makefile : $(MAKEFILE)"
	@cp Libft/$(SUBNAME) $(NAME)
	@ar rcs $@ $^
	@echo "Executable $(NAME) created with $(SUBNAME)."
	
%.o: %.c Makefile ft_printf.h
	@$(CC) $(CFLAGS) -c $< -o $@


compile_submake:
	@echo "Compiling the Makefile : $(SUBMAKEFILE)"
	@$(MAKE) --no-print-directory -C Libft

clean:
	@echo "Delete object files generated by $(SUBMAKEFILE) and $(MAKEFILE)."
	@$(MAKE) --no-print-directory -C Libft clean
	@rm -rf $(OBJ)

fclean: clean
	@echo "Delete complete (including $(SUBNAME) and $(NAME))."
	@$(MAKE) --no-print-directory -C Libft fclean
	@rm -f $(NAME)
	

re: fclean all
